language: python
python: 3.6
addons:
  apt:
    packages:
      - libapt-pkg-dev
      - apt-file
      - expect
      - qemu
  artifacts:
    working_dir: installer
script:
  - make #installcheck
  #- debugfs -R 'rdump */var/log/installer .' disk.img
before_deploy: echo '!stretch/preseed.cfg' > .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  paths: stretch
