#!/bin/bash

set -e

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

apt-get install -y "${APTGETOPT[@]}" lintian

echo "+++ lintian output +++"

su -c "lintian -I --show-overrides '$BUILDDIR'/*.changes; :" - pbuilder

echo "+++ end of lintian output +++"
