source $VIMRUNTIME/defaults.vim
set
  \ hlsearch
  \ nojoinspaces
  \ title
let g:syntastic_auto_loc_list = 1
let g:syntastic_python_checkers = ['python', 'flake8', 'pylint', 'mypy']
let g:syntastic_python_pylint_exec = 'pylint3'
let g:syntastic_python_python_exec = 'python3'
set
  \ ignorecase
  \ smartcase
set
  \ formatoptions-=t
  \ textwidth=72
  \ colorcolumn=+1
